### ISSUE TITLE
functionalities of git

### ISSUE THREAD

**Issue by ramcess** [ramcess/senior#7]
![first git](https://cloud.githubusercontent.com/assets/15088318/10905251/4b46ea18-825c-11e5-81b0-5af4386b6c32.PNG)
![second git](https://cloud.githubusercontent.com/assets/15088318/10905307/b3cc8ba6-825c-11e5-96a2-9798320f303b.PNG)
![third git](https://cloud.githubusercontent.com/assets/15088318/10905310/ba2e25b8-825c-11e5-92ef-97bc3bc8ead4.PNG)
![fourth git](https://cloud.githubusercontent.com/assets/15088318/10905319/c6e4a48a-825c-11e5-8c8e-4386d3476a0b.PNG)
![fifth git](https://cloud.githubusercontent.com/assets/15088318/10905326/d3accce2-825c-11e5-8c27-d444f6407a68.PNG)
![git brach](https://cloud.githubusercontent.com/assets/15088318/10905328/dc98c400-825c-11e5-8c23-3a6bfd1f3969.PNG)
![git log](https://cloud.githubusercontent.com/assets/15088318/10905336/e51bc37a-825c-11e5-9d3e-6aba3d06163d.PNG)
![git push](https://cloud.githubusercontent.com/assets/15088318/10905345/ee6a2b06-825c-11e5-9871-0ccad90276b0.PNG)

**Comment by imeunjung** [comment]
확인했습니다.
